### PR TITLE
Fix for dask 2024.12 and xarray 2024.10, update CI

### LINKED ISSUE #154: Rechunker broken with new xarray and zarr
It looks like rechunker was broken by new versions of xarray for rechunking zarr written to disk.

Minimal working example:
```
import xarray as xr
from rechunker import rechunk
ds = xr.tutorial.open_dataset("air_temperature")
ds.to_zarr('ds1.zarr')
ds = xr.open_zarr('ds1.zarr')
array_plan = rechunk(
    ds, 
    target_chunks={"time": 2920, "lat": 25, "lon": 1},
    max_mem='1GB',
    target_store='ds2.zarr',
    temp_store='temp'
)
```

This worked with version 2024.9.0, but with version 2024.10.0 and up, I get the following error:

```
Traceback (most recent call last):
  File "/exec/jlavoie/.conda/xscen-dev/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-1d0e2ad48247>", line 4, in <module>
    array_plan = rechunk(
                 ^^^^^^^^
  File "/exec/jlavoie/.conda/xscen-dev/lib/python3.12/site-packages/rechunker/api.py", line 303, in rechunk
    copy_spec, intermediate, target = _setup_rechunk(
                                      ^^^^^^^^^^^^^^^
  File "/exec/jlavoie/.conda/xscen-dev/lib/python3.12/site-packages/rechunker/api.py", line 447, in _setup_rechunk
    variable_encoding = extract_zarr_variable_encoding(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/jlavoie/.conda/xscen-dev/lib/python3.12/site-packages/xarray/backends/zarr.py", line 473, in extract_zarr_variable_encoding
    chunks = _determine_zarr_chunks(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/jlavoie/.conda/xscen-dev/lib/python3.12/site-packages/xarray/backends/zarr.py", line 329, in _determine_zarr_chunks
    for zchunk, dchunks, interval, size in zip(
                                           ^^^^
TypeError: 'NoneType' object is not iterable
```

Note that if I don't write ds1 to disk, there is no error.

### LINKED ISSUE #155: Config type string and rechunker plan fails during execution
I have a zarr representing 3D image data ("raw") that I'm able to be open in neuroglancer. I am attempting to rechunk from (1, 256, 256) to (8, 256, 256) using rechunker 0.5.2 installed via pip:

```
from rechunker import rechunk
import zarr

source_array = zarr.open('path/to/3d.zarr/raw')

plan = rechunk(
    source=source_array,
    target_chunks=(8, 256, 256),
    max_mem='1GB',
    target_store='target.zarr',
    temp_store='temp.zarr'
)

plan.execute()
```

However, I'm running into the following error on `plan.execute()`:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/miniconda3/envs/pyrecon_dev/lib/python3.11/site-packages/rechunker/api.py", line 70, in execute
    self._executor.execute_plan(self._plan, **kwargs)
  File "/home/michael/miniconda3/envs/pyrecon_dev/lib/python3.11/site-packages/rechunker/executors/dask.py", line 48, in execute_plan
    return dask.compute(*plan, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/miniconda3/envs/pyrecon_dev/lib/python3.11/site-packages/dask/base.py", line 660, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/miniconda3/envs/pyrecon_dev/lib/python3.11/site-packages/rechunker/executors/dask.py", line 16, in wrapped
    return function(map_arg, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michael/miniconda3/envs/pyrecon_dev/lib/python3.11/site-packages/rechunker/pipeline.py", line 30, in copy_read_to_write
    data = np.asarray(config.read.array[chunk_key])
                      ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'read'
```

I believe the above code did work in the past, though I'm not sure what's going on and why `config` is a string object. Any tips would be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by aulemahal**
This fixes #155, allowing `rechunker` to be used with dask >= 2024.12.0.

The change in dask's `blockwise` was introduced in https://github.com/dask/dask/pull/11568 and requires keys pointing to other dask collections to be wrapped within `TaskRef` objects. The latter were introduced in dask 2024.09, so to preserve retro-compatibility ( `rechunker` doesn't pin  `dask`), I added a if-else that checks dask's version.

I tested against dask 2024.9, 2024.11.2, 2024.12 and 2025.2.

Installing `apache-beam` requires `dask < 2024.8.0` because the former needs `cloudpickle < 2.3` and the latter `>=3`, thus I didn't test if my change had impacts on the  `apache-beam` tests. (I guess it shouldn't...)

EDIT : I added a commit that fixes #154. 

EDIT : I also enabled the CI for the latest python versions and pinned zarr <3. I haven't looked inside the bug with the latest zarr, but it does bug.

### CODE REVIEW

File: rechunker/executors/dask.py [hunk 1]
```diff
@@ -6,9 +6,17 @@
 from dask.blockwise import BlockwiseDepDict, blockwise
 from dask.delayed import Delayed
 from dask.highlevelgraph import HighLevelGraph
+from packaging.version import Version
 
 from rechunker.types import ParallelPipelines, Pipeline, PipelineExecutor
 
+# Change in how dask collection token are given to blockwise()
```
Comment (TomAugspurger) [inline rechunker/executors/dask.py:13]: As of https://github.com/dask/dask/pull/11675, there's a public `dask.task_spec` we can import this from. I think that was released in 2025.1.0.

Could you try adding another version check and importing it from the public location if possible?

**Review by TomAugspurger — COMMENTED** [review]
One small request.

**Comment by aulemahal** [comment]
Done!

**Comment by TomAugspurger** [comment]
The 3.13 CI failed while installing apache-beam: https://github.com/pangeo-data/rechunker/actions/runs/13526734953/job/37827152856?pr=156

presumably because beam or one of its dependencies doesn't have a 3.13 wheel on PyPI. Could you remove that from the matrix and we can get this merged?

**Comment by TomAugspurger** [comment]
Thanks @aulemahal, merging.
